spring:
  application:
    name: gateway
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}
    instance:
      preferIpAddress: true
    registerWithEureka: false
    fetchRegistry: false

app:
  cors:
    allowedOrigins: ${CORS_ALLOWED_ORIGINS}
    allowedMethods: ${CORS_ALLOWED_METHODS}
    allowedHeaders: ${CORS_ALLOWED_HEADERS}
    allowCredentials: ${CORS_ALLOW_CREDENTIALS}